# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actionTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='actionTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x61\x63tionTypeEnum.proto\x12\x06\x63ommon*\xd8\x02\n\x0e\x41\x63tionTypeEnum\x12\x0e\n\nUnknownAct\x10\x00\x12\x0b\n\x07MoveAct\x10\x01\x12\x14\n\x10Plan4ExchangeAct\x10\x02\x12\x0c\n\x08\x43heckAct\x10\x03\x12\x0f\n\x0b\x43ountingAct\x10\x04\x12\x12\n\x0eLoadBalanceAct\x10\x05\x12\x0f\n\x0b\x45xchangeAct\x10\x06\x12\x0b\n\x07LoadAct\x10\x07\x12\r\n\tChoiceAct\x10\x08\x12\x13\n\x0f\x43hangeStatusAct\x10\t\x12\n\n\x06OutAct\x10\x65\x12\t\n\x05InAct\x10\x66\x12\x0b\n\x07LockAct\x10g\x12\r\n\tUnLockAct\x10h\x12\x18\n\x14\x43reateWO4ExchangeAct\x10n\x12\x12\n\x0e\x43reateWO4IBAct\x10o\x12\x12\n\x0e\x43reateWO4OBAct\x10p\x12\x18\n\x14\x43reateWO4TransferAct\x10q\x12\x0f\n\x0b\x43learCtxAct\x10xBf\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_ACTIONTYPEENUM = _descriptor.EnumDescriptor(
  name='ActionTypeEnum',
  full_name='common.ActionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownAct', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MoveAct', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Plan4ExchangeAct', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CheckAct', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CountingAct', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LoadBalanceAct', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ExchangeAct', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LoadAct', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ChoiceAct', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ChangeStatusAct', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OutAct', index=10, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InAct', index=11, number=102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LockAct', index=12, number=103,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UnLockAct', index=13, number=104,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CreateWO4ExchangeAct', index=14, number=110,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CreateWO4IBAct', index=15, number=111,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CreateWO4OBAct', index=16, number=112,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CreateWO4TransferAct', index=17, number=113,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ClearCtxAct', index=18, number=120,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=33,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPEENUM)

ActionTypeEnum = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPEENUM)
UnknownAct = 0
MoveAct = 1
Plan4ExchangeAct = 2
CheckAct = 3
CountingAct = 4
LoadBalanceAct = 5
ExchangeAct = 6
LoadAct = 7
ChoiceAct = 8
ChangeStatusAct = 9
OutAct = 101
InAct = 102
LockAct = 103
UnLockAct = 104
CreateWO4ExchangeAct = 110
CreateWO4IBAct = 111
CreateWO4OBAct = 112
CreateWO4TransferAct = 113
ClearCtxAct = 120


DESCRIPTOR.enum_types_by_name['ActionTypeEnum'] = _ACTIONTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
