# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actionStatusEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='actionStatusEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61\x63tionStatusEnum.proto\x12\x06\x63ommon*\xb8\x01\n\x10\x41\x63tionStatusEnum\x12\x18\n\x14\x41\x63tionStatusTypeInit\x10\x00\x12\x1e\n\x1a\x41\x63tionStatusTypeProcessing\x10\x01\x12\x18\n\x14\x41\x63tionStatusTypeDone\x10\x02\x12\x1a\n\x16\x41\x63tionStatusTypeCancel\x10\t\x12\x1a\n\x16\x41\x63tionStatusTypeFailed\x10\n\x12\x18\n\x14\x41\x63tionStatusTypeTemp\x10\x14\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_ACTIONSTATUSENUM = _descriptor.EnumDescriptor(
  name='ActionStatusEnum',
  full_name='common.ActionStatusEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ActionStatusTypeInit', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ActionStatusTypeProcessing', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ActionStatusTypeDone', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ActionStatusTypeCancel', index=3, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ActionStatusTypeFailed', index=4, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ActionStatusTypeTemp', index=5, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=35,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_ACTIONSTATUSENUM)

ActionStatusEnum = enum_type_wrapper.EnumTypeWrapper(_ACTIONSTATUSENUM)
ActionStatusTypeInit = 0
ActionStatusTypeProcessing = 1
ActionStatusTypeDone = 2
ActionStatusTypeCancel = 9
ActionStatusTypeFailed = 10
ActionStatusTypeTemp = 20


DESCRIPTOR.enum_types_by_name['ActionStatusEnum'] = _ACTIONSTATUSENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
