# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containerTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='containerTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63ontainerTypeEnum.proto\x12\x06\x63ommon*\xd7\x01\n\x11\x43ontainerTypeEnum\x12\x18\n\x14\x43ontainerTypeUnknown\x10\x00\x12\x1c\n\x18\x43ontainerTypeOriginalBox\x10\x01\x12\x1c\n\x18\x43ontainerTypeCircularBox\x10\x02\x12\x17\n\x13\x43ontainerTypePallet\x10\x03\x12\x19\n\x15\x43ontainerTypeAgvShelf\x10\x04\x12\x1c\n\x18\x43ontainerTypeSowingShelf\x10\x05\x12\x1a\n\x16\x43ontainerTypeBeamShelf\x10\x06\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_CONTAINERTYPEENUM = _descriptor.EnumDescriptor(
  name='ContainerTypeEnum',
  full_name='common.ContainerTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ContainerTypeUnknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ContainerTypeOriginalBox', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ContainerTypeCircularBox', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ContainerTypePallet', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ContainerTypeAgvShelf', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ContainerTypeSowingShelf', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ContainerTypeBeamShelf', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=36,
  serialized_end=251,
)
_sym_db.RegisterEnumDescriptor(_CONTAINERTYPEENUM)

ContainerTypeEnum = enum_type_wrapper.EnumTypeWrapper(_CONTAINERTYPEENUM)
ContainerTypeUnknown = 0
ContainerTypeOriginalBox = 1
ContainerTypeCircularBox = 2
ContainerTypePallet = 3
ContainerTypeAgvShelf = 4
ContainerTypeSowingShelf = 5
ContainerTypeBeamShelf = 6


DESCRIPTOR.enum_types_by_name['ContainerTypeEnum'] = _CONTAINERTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
