# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: desTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='desTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x65sTypeEnum.proto\x12\x06\x63ommon*k\n\x0b\x44\x65sTypeEnum\x12\x12\n\x0e\x44\x65sTypeUNKNOWN\x10\x00\x12\x0f\n\x0b\x44\x65sTypeNode\x10\x01\x12\x12\n\x0e\x44\x65sTypeStorage\x10\x02\x12\x0f\n\x0b\x44\x65sTypeZone\x10\x03\x12\x12\n\x0e\x44\x65sTypeStation\x10\x64\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_DESTYPEENUM = _descriptor.EnumDescriptor(
  name='DesTypeEnum',
  full_name='common.DesTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DesTypeUNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DesTypeNode', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DesTypeStorage', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DesTypeZone', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DesTypeStation', index=4, number=100,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=29,
  serialized_end=136,
)
_sym_db.RegisterEnumDescriptor(_DESTYPEENUM)

DesTypeEnum = enum_type_wrapper.EnumTypeWrapper(_DESTYPEENUM)
DesTypeUNKNOWN = 0
DesTypeNode = 1
DesTypeStorage = 2
DesTypeZone = 3
DesTypeStation = 100


DESCRIPTOR.enum_types_by_name['DesTypeEnum'] = _DESTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
