# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lockReasonEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lockReasonEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14lockReasonEnum.proto\x12\x06\x63ommon*\'\n\x0eLockReasonEnum\x12\x15\n\x11LockReasonUNKNOWN\x10\x00\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_LOCKREASONENUM = _descriptor.EnumDescriptor(
  name='LockReasonEnum',
  full_name='common.LockReasonEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LockReasonUNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=71,
)
_sym_db.RegisterEnumDescriptor(_LOCKREASONENUM)

LockReasonEnum = enum_type_wrapper.EnumTypeWrapper(_LOCKREASONENUM)
LockReasonUNKNOWN = 0


DESCRIPTOR.enum_types_by_name['LockReasonEnum'] = _LOCKREASONENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
