# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regionTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='regionTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14regionTypeEnum.proto\x12\x06\x63ommon*\xa3\x01\n\x0eRegionTypeEnum\x12\x15\n\x11RegionTypeUnknown\x10\x00\x12\x10\n\x0cRegionTypePS\x10\x01\x12\x11\n\rRegionTypeCTU\x10\x02\x12\x10\n\x0cRegionTypeFA\x10\x03\x12\x17\n\x13RegionTypeReceiving\x10\x04\x12\x12\n\x0eRegionTypePeak\x10\x05\x12\x16\n\x12RegionTypeExchange\x10\x06\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_REGIONTYPEENUM = _descriptor.EnumDescriptor(
  name='RegionTypeEnum',
  full_name='common.RegionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RegionTypeUnknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RegionTypePS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RegionTypeCTU', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RegionTypeFA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RegionTypeReceiving', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RegionTypePeak', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RegionTypeExchange', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=33,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_REGIONTYPEENUM)

RegionTypeEnum = enum_type_wrapper.EnumTypeWrapper(_REGIONTYPEENUM)
RegionTypeUnknown = 0
RegionTypePS = 1
RegionTypeCTU = 2
RegionTypeFA = 3
RegionTypeReceiving = 4
RegionTypePeak = 5
RegionTypeExchange = 6


DESCRIPTOR.enum_types_by_name['RegionTypeEnum'] = _REGIONTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
