# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stationCodeTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stationCodeTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19stationCodeTypeEnum.proto\x12\x06\x63ommon*Y\n\x13StationCodeTypeEnum\x12\x13\n\x0f\x43odeTypeUNKNOWN\x10\x00\x12\x13\n\x0f\x43odeTypeStation\x10\x01\x12\x18\n\x14\x43odeTypeStationGroup\x10\x02\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_STATIONCODETYPEENUM = _descriptor.EnumDescriptor(
  name='StationCodeTypeEnum',
  full_name='common.StationCodeTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CodeTypeUNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CodeTypeStation', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CodeTypeStationGroup', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=37,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_STATIONCODETYPEENUM)

StationCodeTypeEnum = enum_type_wrapper.EnumTypeWrapper(_STATIONCODETYPEENUM)
CodeTypeUNKNOWN = 0
CodeTypeStation = 1
CodeTypeStationGroup = 2


DESCRIPTOR.enum_types_by_name['StationCodeTypeEnum'] = _STATIONCODETYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
