# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tesReporterTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tesReporterTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19tesReporterTypeEnum.proto\x12\x06\x63ommon*@\n\x13TesReporterTypeEnum\x12\x13\n\x0fReporterTypeBCR\x10\x00\x12\x14\n\x10ReporterTypeRFID\x10\x01\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_TESREPORTERTYPEENUM = _descriptor.EnumDescriptor(
  name='TesReporterTypeEnum',
  full_name='common.TesReporterTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ReporterTypeBCR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ReporterTypeRFID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=37,
  serialized_end=101,
)
_sym_db.RegisterEnumDescriptor(_TESREPORTERTYPEENUM)

TesReporterTypeEnum = enum_type_wrapper.EnumTypeWrapper(_TESREPORTERTYPEENUM)
ReporterTypeBCR = 0
ReporterTypeRFID = 1


DESCRIPTOR.enum_types_by_name['TesReporterTypeEnum'] = _TESREPORTERTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
