# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tesStatusEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tesStatusEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13tesStatusEnum.proto\x12\x06\x63ommon*\x8e\x01\n\rTesStatusEnum\x12\x0e\n\nStatusINIT\x10\x00\x12\x0f\n\x0bStatusREADY\x10\x01\x12\x11\n\rStatusRUNNING\x10\x02\x12\x0e\n\nStatusDONE\x10\x04\x12\x10\n\x0cStatusFAILED\x10\x05\x12\x13\n\x0fStatusCANCELING\x10\x03\x12\x12\n\x0eStatusCANCELED\x10\x06\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_TESSTATUSENUM = _descriptor.EnumDescriptor(
  name='TesStatusEnum',
  full_name='common.TesStatusEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='StatusINIT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='StatusREADY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='StatusRUNNING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='StatusDONE', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='StatusFAILED', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='StatusCANCELING', index=5, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='StatusCANCELED', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=174,
)
_sym_db.RegisterEnumDescriptor(_TESSTATUSENUM)

TesStatusEnum = enum_type_wrapper.EnumTypeWrapper(_TESSTATUSENUM)
StatusINIT = 0
StatusREADY = 1
StatusRUNNING = 2
StatusDONE = 4
StatusFAILED = 5
StatusCANCELING = 3
StatusCANCELED = 6


DESCRIPTOR.enum_types_by_name['TesStatusEnum'] = _TESSTATUSENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
