# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tesTaskTypEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tesTaskTypEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14tesTaskTypEnum.proto\x12\x06\x63ommon*\x96\x01\n\x0eTesTaskTypEnum\x12\x13\n\x0fTaskTypeUNKNOWN\x10\x00\x12\x16\n\x12TaskTypeMOVE_ROBOT\x10\x02\x12\x14\n\x10TaskTypeMOVE_POD\x10\x03\x12\x15\n\x11TaskTypeGO_CHARGE\x10\x04\x12\x16\n\x12TaskTypeCHANGE_MAP\x10\x05\x12\x12\n\x0eTaskTypeCUSTOM\x10<Bf\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_TESTASKTYPENUM = _descriptor.EnumDescriptor(
  name='TesTaskTypEnum',
  full_name='common.TesTaskTypEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TaskTypeUNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TaskTypeMOVE_ROBOT', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TaskTypeMOVE_POD', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TaskTypeGO_CHARGE', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TaskTypeCHANGE_MAP', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TaskTypeCUSTOM', index=5, number=60,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=33,
  serialized_end=183,
)
_sym_db.RegisterEnumDescriptor(_TESTASKTYPENUM)

TesTaskTypEnum = enum_type_wrapper.EnumTypeWrapper(_TESTASKTYPENUM)
TaskTypeUNKNOWN = 0
TaskTypeMOVE_ROBOT = 2
TaskTypeMOVE_POD = 3
TaskTypeGO_CHARGE = 4
TaskTypeCHANGE_MAP = 5
TaskTypeCUSTOM = 60


DESCRIPTOR.enum_types_by_name['TesTaskTypEnum'] = _TESTASKTYPENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
