# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13transTypeEnum.proto\x12\x06\x63ommon*\xbe\x02\n\rTransTypeEnum\x12\x14\n\x10TrasnTypeUNKNOWN\x10\x00\x12\r\n\tCartonAdd\x10\x01\x12\x0f\n\x0b\x45xchangeAdd\x10\x02\x12\r\n\tCartonOut\x10\x03\x12\x0b\n\x07PickOut\x10\x04\x12\x0c\n\x08\x43\x61rtonIn\x10\x05\x12\x0e\n\nExchangeIn\x10\x06\x12\n\n\x06TailIn\x10\x07\x12\r\n\tInventory\x10\x08\x12\n\n\x06\x43TUOut\x10\t\x12\x0e\n\nCTUCombine\x10\n\x12\t\n\x05\x43TUIn\x10\x0b\x12\t\n\x05\x43TUOB\x10\x0c\x12\x0e\n\nPSNormalIn\x10\r\x12\r\n\tPSCollect\x10\x0e\x12\n\n\x06PSTail\x10\x0f\x12\x0f\n\x0bPSPalletOut\x10\x10\x12\x0e\n\nPSPalletIn\x10\x11\x12\x0c\n\x08PSCarton\x10\x65\x12\x0b\n\x07PSCrate\x10\x66\x12\t\n\x05PSArm\x10gBf\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_TRANSTYPEENUM = _descriptor.EnumDescriptor(
  name='TransTypeEnum',
  full_name='common.TransTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TrasnTypeUNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CartonAdd', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ExchangeAdd', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CartonOut', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PickOut', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CartonIn', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ExchangeIn', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TailIn', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Inventory', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CTUOut', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CTUCombine', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CTUIn', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CTUOB', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSNormalIn', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSCollect', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSTail', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSPalletOut', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSPalletIn', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSCarton', index=18, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSCrate', index=19, number=102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PSArm', index=20, number=103,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=350,
)
_sym_db.RegisterEnumDescriptor(_TRANSTYPEENUM)

TransTypeEnum = enum_type_wrapper.EnumTypeWrapper(_TRANSTYPEENUM)
TrasnTypeUNKNOWN = 0
CartonAdd = 1
ExchangeAdd = 2
CartonOut = 3
PickOut = 4
CartonIn = 5
ExchangeIn = 6
TailIn = 7
Inventory = 8
CTUOut = 9
CTUCombine = 10
CTUIn = 11
CTUOB = 12
PSNormalIn = 13
PSCollect = 14
PSTail = 15
PSPalletOut = 16
PSPalletIn = 17
PSCarton = 101
PSCrate = 102
PSArm = 103


DESCRIPTOR.enum_types_by_name['TransTypeEnum'] = _TRANSTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
