# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workOrderTypeEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='workOrderTypeEnum.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'\n\036com.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17workOrderTypeEnum.proto\x12\x06\x63ommon*\x8d\x01\n\x11WorkOrderTypeEnum\x12\x11\n\rWoTypeUNKNOWN\x10\x00\x12\x0f\n\x0bWoTypeWo4ib\x10\x0b\x12\x0f\n\x0bWoTypeWo4ob\x10\x0c\x12\x15\n\x11WoTypeWo4exchange\x10\r\x12\x15\n\x11WoTypeWo4transfer\x10\x0e\x12\x15\n\x11WoTypeWo4counting\x10\x0f\x42\x66\n\x1e\x63om.megvii.lbg.wes.grpc.commonZDgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/commonb\x06proto3'
)

_WORKORDERTYPEENUM = _descriptor.EnumDescriptor(
  name='WorkOrderTypeEnum',
  full_name='common.WorkOrderTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WoTypeUNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WoTypeWo4ib', index=1, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WoTypeWo4ob', index=2, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WoTypeWo4exchange', index=3, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WoTypeWo4transfer', index=4, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WoTypeWo4counting', index=5, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=36,
  serialized_end=177,
)
_sym_db.RegisterEnumDescriptor(_WORKORDERTYPEENUM)

WorkOrderTypeEnum = enum_type_wrapper.EnumTypeWrapper(_WORKORDERTYPEENUM)
WoTypeUNKNOWN = 0
WoTypeWo4ib = 11
WoTypeWo4ob = 12
WoTypeWo4exchange = 13
WoTypeWo4transfer = 14
WoTypeWo4counting = 15


DESCRIPTOR.enum_types_by_name['WorkOrderTypeEnum'] = _WORKORDERTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
