# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from psgrpc.common import common_pb2 as common__pb2
#import mastercontrol_pb2 as mastercontrol_pb2
from psgrpc.wareshuttle import mastercontrol_pb2 as mastercontrol__pb2



class MasterControlStub(object):
    """ProcessFlowEngine engine message channel
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WaveTrigger = channel.unary_unary(
                '/wareshuttle.MasterControl/WaveTrigger',
                request_serializer=mastercontrol__pb2.WareTriggerRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )


class MasterControlServicer(object):
    """ProcessFlowEngine engine message channel
    """

    def WaveTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WaveTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.WaveTrigger,
                    request_deserializer=mastercontrol__pb2.WareTriggerRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wareshuttle.MasterControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterControl(object):
    """ProcessFlowEngine engine message channel
    """

    @staticmethod
    def WaveTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wareshuttle.MasterControl/WaveTrigger',
            mastercontrol__pb2.WareTriggerRequest.SerializeToString,
            common__pb2.CommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
