# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastercontrol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from psgrpc.common import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mastercontrol.proto',
  package='wareshuttle',
  syntax='proto3',
  serialized_options=b'ZGgit-pd.megvii-inc.com/slg-service/wareshuttle/internal/grpc/wareshuttle',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13mastercontrol.proto\x12\x0bwareshuttle\x1a\x0c\x63ommon.proto\"d\n\x12WareTriggerRequest\x12\x0f\n\x07traceID\x18\x01 \x01(\t\x12\x15\n\rwarehouseCode\x18\x02 \x01(\t\x12\x12\n\nregionCode\x18\x03 \x01(\t\x12\x12\n\nwaveNoList\x18\x04 \x03(\t2Y\n\rMasterControl\x12H\n\x0bWaveTrigger\x12\x1f.wareshuttle.WareTriggerRequest\x1a\x16.common.CommonResponse\"\x00\x42IZGgit-pd.megvii-inc.com/slg-service/wareshuttle/internal/grpc/wareshuttleb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_WARETRIGGERREQUEST = _descriptor.Descriptor(
  name='WareTriggerRequest',
  full_name='wareshuttle.WareTriggerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='traceID', full_name='wareshuttle.WareTriggerRequest.traceID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warehouseCode', full_name='wareshuttle.WareTriggerRequest.warehouseCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regionCode', full_name='wareshuttle.WareTriggerRequest.regionCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='waveNoList', full_name='wareshuttle.WareTriggerRequest.waveNoList', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['WareTriggerRequest'] = _WARETRIGGERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WareTriggerRequest = _reflection.GeneratedProtocolMessageType('WareTriggerRequest', (_message.Message,), {
  'DESCRIPTOR' : _WARETRIGGERREQUEST,
  '__module__' : 'mastercontrol_pb2'
  # @@protoc_insertion_point(class_scope:wareshuttle.WareTriggerRequest)
  })
_sym_db.RegisterMessage(WareTriggerRequest)


DESCRIPTOR._options = None

_MASTERCONTROL = _descriptor.ServiceDescriptor(
  name='MasterControl',
  full_name='wareshuttle.MasterControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=152,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='WaveTrigger',
    full_name='wareshuttle.MasterControl.WaveTrigger',
    index=0,
    containing_service=None,
    input_type=_WARETRIGGERREQUEST,
    output_type=common__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERCONTROL)

DESCRIPTOR.services_by_name['MasterControl'] = _MASTERCONTROL

# @@protoc_insertion_point(module_scope)
