# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from psgrpc.common import common_pb2 as common__pb2
from psgrpc.common import station_pb2 as station__pb2


class StationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStation = channel.unary_unary(
                '/warebasic.StationService/AddStation',
                request_serializer=station__pb2.AddStationRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )
        self.QueryStationList = channel.unary_unary(
                '/warebasic.StationService/QueryStationList',
                request_serializer=station__pb2.QueryStationListRequest.SerializeToString,
                response_deserializer=station__pb2.QueryStationListResponse.FromString,
                )
        self.QueryStationDetail = channel.unary_unary(
                '/warebasic.StationService/QueryStationDetail',
                request_serializer=station__pb2.QueryStationDetailRequest.SerializeToString,
                response_deserializer=station__pb2.QueryStationDetailResponse.FromString,
                )
        self.UpdateStation = channel.unary_unary(
                '/warebasic.StationService/UpdateStation',
                request_serializer=station__pb2.UpdateStationRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )
        self.EnableStation = channel.unary_unary(
                '/warebasic.StationService/EnableStation',
                request_serializer=station__pb2.EnableStationRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )
        self.DisableStation = channel.unary_unary(
                '/warebasic.StationService/DisableStation',
                request_serializer=station__pb2.DisableStationRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )


class StationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddStation(self, request, context):
        """新增工作站
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStationList(self, request, context):
        """查询工作站列表
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStationDetail(self, request, context):
        """查询工作站详情
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStation(self, request, context):
        """更新工作站
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableStation(self, request, context):
        """启用工作站
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableStation(self, request, context):
        """禁用工作站
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStation': psgrpc.unary_unary_rpc_method_handler(
                    servicer.AddStation,
                    request_deserializer=station__pb2.AddStationRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
            'QueryStationList': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryStationList,
                    request_deserializer=station__pb2.QueryStationListRequest.FromString,
                    response_serializer=station__pb2.QueryStationListResponse.SerializeToString,
            ),
            'QueryStationDetail': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryStationDetail,
                    request_deserializer=station__pb2.QueryStationDetailRequest.FromString,
                    response_serializer=station__pb2.QueryStationDetailResponse.SerializeToString,
            ),
            'UpdateStation': psgrpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStation,
                    request_deserializer=station__pb2.UpdateStationRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
            'EnableStation': psgrpc.unary_unary_rpc_method_handler(
                    servicer.EnableStation,
                    request_deserializer=station__pb2.EnableStationRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
            'DisableStation': psgrpc.unary_unary_rpc_method_handler(
                    servicer.DisableStation,
                    request_deserializer=station__pb2.DisableStationRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
    }
    generic_handler = psgrpc.method_handlers_generic_handler(
            'warebasic.StationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationService/AddStation',
                                               station__pb2.AddStationRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStationList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationService/QueryStationList',
                                               station__pb2.QueryStationListRequest.SerializeToString,
                                               station__pb2.QueryStationListResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStationDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationService/QueryStationDetail',
                                               station__pb2.QueryStationDetailRequest.SerializeToString,
                                               station__pb2.QueryStationDetailResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationService/UpdateStation',
                                               station__pb2.UpdateStationRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationService/EnableStation',
                                               station__pb2.EnableStationRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationService/DisableStation',
                                               station__pb2.DisableStationRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
