# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from psgrpc.common import common_pb2 as common__pb2
from psgrpc.common  import stationGroup_pb2 as stationGroup__pb2


class StationGroupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStationGroup = channel.unary_unary(
                '/warebasic.StationGroupService/AddStationGroup',
                request_serializer=stationGroup__pb2.AddStationGroupRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )
        self.QueryStationGroupList = channel.unary_unary(
                '/warebasic.StationGroupService/QueryStationGroupList',
                request_serializer=stationGroup__pb2.QueryStationGroupListRequest.SerializeToString,
                response_deserializer=stationGroup__pb2.QueryStationGroupListResponse.FromString,
                )
        self.QueryStationGroupDetail = channel.unary_unary(
                '/warebasic.StationGroupService/QueryStationGroupDetail',
                request_serializer=stationGroup__pb2.QueryStationGroupDetailRequest.SerializeToString,
                response_deserializer=stationGroup__pb2.QueryStationGroupDetailResponse.FromString,
                )


class StationGroupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddStationGroup(self, request, context):
        """新增工作站组
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStationGroupList(self, request, context):
        """查询工作站组列表
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStationGroupDetail(self, request, context):
        """查询工作站组详情
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StationGroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStationGroup': psgrpc.unary_unary_rpc_method_handler(
                    servicer.AddStationGroup,
                    request_deserializer=stationGroup__pb2.AddStationGroupRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
            'QueryStationGroupList': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryStationGroupList,
                    request_deserializer=stationGroup__pb2.QueryStationGroupListRequest.FromString,
                    response_serializer=stationGroup__pb2.QueryStationGroupListResponse.SerializeToString,
            ),
            'QueryStationGroupDetail': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryStationGroupDetail,
                    request_deserializer=stationGroup__pb2.QueryStationGroupDetailRequest.FromString,
                    response_serializer=stationGroup__pb2.QueryStationGroupDetailResponse.SerializeToString,
            ),
    }
    generic_handler = psgrpc.method_handlers_generic_handler(
            'warebasic.StationGroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StationGroupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddStationGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationGroupService/AddStationGroup',
                                               stationGroup__pb2.AddStationGroupRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStationGroupList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationGroupService/QueryStationGroupList',
                                               stationGroup__pb2.QueryStationGroupListRequest.SerializeToString,
                                               stationGroup__pb2.QueryStationGroupListResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStationGroupDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StationGroupService/QueryStationGroupDetail',
                                               stationGroup__pb2.QueryStationGroupDetailRequest.SerializeToString,
                                               stationGroup__pb2.QueryStationGroupDetailResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
