# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from psgrpc.common import common_pb2 as common__pb2
from psgrpc.common import storage_pb2 as storage__pb2


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStorage = channel.unary_unary(
                '/warebasic.StorageService/AddStorage',
                request_serializer=storage__pb2.AddStorageRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )
        self.QueryStorageList = channel.unary_unary(
                '/warebasic.StorageService/QueryStorageList',
                request_serializer=storage__pb2.QueryStorageListRequest.SerializeToString,
                response_deserializer=storage__pb2.QueryStorageListResponse.FromString,
                )
        self.QueryStorageDetail = channel.unary_unary(
                '/warebasic.StorageService/QueryStorageDetail',
                request_serializer=storage__pb2.QueryStorageDetailRequest.SerializeToString,
                response_deserializer=storage__pb2.QueryStorageDetailResponse.FromString,
                )
        self.UpdateStorage = channel.unary_unary(
                '/warebasic.StorageService/UpdateStorage',
                request_serializer=storage__pb2.UpdateStorageRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddStorage(self, request, context):
        """新增存储区
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStorageList(self, request, context):
        """查询存储区列表
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStorageDetail(self, request, context):
        """查询存储区详情
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStorage(self, request, context):
        """更新存储区
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStorage': psgrpc.unary_unary_rpc_method_handler(
                    servicer.AddStorage,
                    request_deserializer=storage__pb2.AddStorageRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
            'QueryStorageList': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryStorageList,
                    request_deserializer=storage__pb2.QueryStorageListRequest.FromString,
                    response_serializer=storage__pb2.QueryStorageListResponse.SerializeToString,
            ),
            'QueryStorageDetail': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryStorageDetail,
                    request_deserializer=storage__pb2.QueryStorageDetailRequest.FromString,
                    response_serializer=storage__pb2.QueryStorageDetailResponse.SerializeToString,
            ),
            'UpdateStorage': psgrpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStorage,
                    request_deserializer=storage__pb2.UpdateStorageRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
    }
    generic_handler = psgrpc.method_handlers_generic_handler(
            'warebasic.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StorageService/AddStorage',
                                               storage__pb2.AddStorageRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStorageList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StorageService/QueryStorageList',
                                               storage__pb2.QueryStorageListRequest.SerializeToString,
                                               storage__pb2.QueryStorageListResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStorageDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StorageService/QueryStorageDetail',
                                               storage__pb2.QueryStorageDetailRequest.SerializeToString,
                                               storage__pb2.QueryStorageDetailResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.StorageService/UpdateStorage',
                                               storage__pb2.UpdateStorageRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
