# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from psgrpc.common import common_pb2 as common__pb2
from psgrpc.common import warehouse_pb2 as warehouse__pb2


class WarehouseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWarehouse = channel.unary_unary(
                '/warebasic.WarehouseService/RegisterWarehouse',
                request_serializer=warehouse__pb2.RegisterWarehouseRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )
        self.QueryAllWarehouse = channel.unary_unary(
                '/warebasic.WarehouseService/QueryAllWarehouse',
                request_serializer=warehouse__pb2.QueryAllWarehouseRequest.SerializeToString,
                response_deserializer=warehouse__pb2.QueryAllWarehouseResponse.FromString,
                )
        self.QueryWarehouseDetail = channel.unary_unary(
                '/warebasic.WarehouseService/QueryWarehouseDetail',
                request_serializer=warehouse__pb2.QueryWarehouseDetailRequest.SerializeToString,
                response_deserializer=warehouse__pb2.QueryWarehouseDetailResponse.FromString,
                )
        self.UpdateWarehouse = channel.unary_unary(
                '/warebasic.WarehouseService/UpdateWarehouse',
                request_serializer=warehouse__pb2.UpdateWarehouseRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )


class WarehouseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWarehouse(self, request, context):
        """注册仓库
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAllWarehouse(self, request, context):
        """查询所有仓库
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryWarehouseDetail(self, request, context):
        """查询仓库详情
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWarehouse(self, request, context):
        """更新仓库
        """
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWarehouse': psgrpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWarehouse,
                    request_deserializer=warehouse__pb2.RegisterWarehouseRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
            'QueryAllWarehouse': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryAllWarehouse,
                    request_deserializer=warehouse__pb2.QueryAllWarehouseRequest.FromString,
                    response_serializer=warehouse__pb2.QueryAllWarehouseResponse.SerializeToString,
            ),
            'QueryWarehouseDetail': psgrpc.unary_unary_rpc_method_handler(
                    servicer.QueryWarehouseDetail,
                    request_deserializer=warehouse__pb2.QueryWarehouseDetailRequest.FromString,
                    response_serializer=warehouse__pb2.QueryWarehouseDetailResponse.SerializeToString,
            ),
            'UpdateWarehouse': psgrpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWarehouse,
                    request_deserializer=warehouse__pb2.UpdateWarehouseRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
    }
    generic_handler = psgrpc.method_handlers_generic_handler(
            'warebasic.WarehouseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WarehouseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWarehouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.WarehouseService/RegisterWarehouse',
                                               warehouse__pb2.RegisterWarehouseRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryAllWarehouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.WarehouseService/QueryAllWarehouse',
                                               warehouse__pb2.QueryAllWarehouseRequest.SerializeToString,
                                               warehouse__pb2.QueryAllWarehouseResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryWarehouseDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.WarehouseService/QueryWarehouseDetail',
                                               warehouse__pb2.QueryWarehouseDetailRequest.SerializeToString,
                                               warehouse__pb2.QueryWarehouseDetailResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateWarehouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/warebasic.WarehouseService/UpdateWarehouse',
                                               warehouse__pb2.UpdateWarehouseRequest.SerializeToString,
                                               common__pb2.CommonResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
