# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from psgrpc.common  import parameters_pb2 as parameters__pb2


class ProcessFlowEngineStub(object):
    """ProcessFlowEngine engine message channel
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnceChannel = channel.unary_unary(
                '/frworkstation.ProcessFlowEngine/OnceChannel',
                request_serializer=parameters__pb2.ServerPackage.SerializeToString,
                response_deserializer=parameters__pb2.ClientPackage.FromString,
                )


class ProcessFlowEngineServicer(object):
    """ProcessFlowEngine engine message channel
    """

    def OnceChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(psgrpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessFlowEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnceChannel': psgrpc.unary_unary_rpc_method_handler(
                    servicer.OnceChannel,
                    request_deserializer=parameters__pb2.ServerPackage.FromString,
                    response_serializer=parameters__pb2.ClientPackage.SerializeToString,
            ),
    }
    generic_handler = psgrpc.method_handlers_generic_handler(
            'frworkstation.ProcessFlowEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessFlowEngine(object):
    """ProcessFlowEngine engine message channel
    """

    @staticmethod
    def OnceChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return psgrpc.experimental.unary_unary(request, target, '/frworkstation.ProcessFlowEngine/OnceChannel',
                                               parameters__pb2.ServerPackage.SerializeToString,
                                               parameters__pb2.ClientPackage.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
