# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frworkstation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from psgrpc.common import parameters_pb2 as parameters__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='frworkstation.proto',
  package='frworkstation',
  syntax='proto3',
  serialized_options=b'\n%com.megvii.lbg.wes.grpc.frworkstationB\rFRWorkStationP\001ZKgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/frworkstation',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66rworkstation.proto\x12\rfrworkstation\x1a\x10parameters.proto2R\n\x11ProcessFlowEngine\x12=\n\x0bOnceChannel\x12\x15.common.ServerPackage\x1a\x15.common.ClientPackage\"\x00\x42\x85\x01\n%com.megvii.lbg.wes.grpc.frworkstationB\rFRWorkStationP\x01ZKgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/frworkstationb\x06proto3'
  ,
  dependencies=[parameters__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_PROCESSFLOWENGINE = _descriptor.ServiceDescriptor(
  name='ProcessFlowEngine',
  full_name='frworkstation.ProcessFlowEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=56,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='OnceChannel',
    full_name='frworkstation.ProcessFlowEngine.OnceChannel',
    index=0,
    containing_service=None,
    input_type=parameters__pb2._SERVERPACKAGE,
    output_type=parameters__pb2._CLIENTPACKAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROCESSFLOWENGINE)

DESCRIPTOR.services_by_name['ProcessFlowEngine'] = _PROCESSFLOWENGINE

# @@protoc_insertion_point(module_scope)
